package sean.com.example.notetest.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sean.com.example.notetest.entity.EventsInfo;

import sean.com.example.notetest.db.EventsInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventsInfoDaoConfig;

    private final EventsInfoDao eventsInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventsInfoDaoConfig = daoConfigMap.get(EventsInfoDao.class).clone();
        eventsInfoDaoConfig.initIdentityScope(type);

        eventsInfoDao = new EventsInfoDao(eventsInfoDaoConfig, this);

        registerDao(EventsInfo.class, eventsInfoDao);
    }
    
    public void clear() {
        eventsInfoDaoConfig.clearIdentityScope();
    }

    public EventsInfoDao getEventsInfoDao() {
        return eventsInfoDao;
    }

}
